### PR TITLE
fixes bugs from ped

### LINKED ISSUE #95: [PE-D][Tester A] help function
help function is still able to work even if more words are added. 

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: AaaaaronC/ped#6

### LINKED ISSUE #101: [PE-D][Tester C] Setting biometrics is case sensitive
Does not accept MALE as gender, only accepts male.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: eehongchan/ped#4

### LINKED ISSUE #106: [PE-D][Tester C] Bug when entering 100% fat percentage
Input rejected when setting fat percentage to 100%, although in UG it is stated that fat percentage can be between 0% to 100%.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: eehongchan/ped#5

### LINKED ISSUE #123: [PE-D][Tester A] error message for add weight
error message is of a very different format from other error messages.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: AaaaaronC/ped#11

### LINKED ISSUE #141: [PE-D][Tester A] typo in help message
no curly brackets around height

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: AaaaaronC/ped#14

### LINKED ISSUE #160: Code review for @maanyos
# @maanyos

- [ ] Remove these [magic numbers](https://nus-cs2113-ay2223s1.github.io/website/se-book-adapted/chapters/codeQuality.html#avoid-magic-numbers)

https://github.com/AY2223S1-CS2113-W12-3/tp/blob/b6a63d8f3719e989c4db9c2e8f0ab4ad03c899ba/src/main/java/seedu/duke/records/biometrics/WeightAndFat.java#L44-L54

https://github.com/AY2223S1-CS2113-W12-3/tp/blob/b6a63d8f3719e989c4db9c2e8f0ab4ad03c899ba/src/main/java/seedu/duke/records/biometrics/Biometrics.java#L66-L85

### PR DESCRIPTION
**Pull request by maanyos**
fixes #160 fixes #141 fixes #123 fixes #106 fixes #101 fixes #95 
refacotred date parser for add command

### CODE REVIEW

File: src/main/java/seedu/duke/command/AddCommand.java [hunk 1]
```diff
@@ -232,15 +232,15 @@ private void addFood(String[] argumentList) throws IllegalValueException {
 
 
     private void addWeightAndFat(String[] argumentList) throws IllegalValueException {
-        if (argumentList.length < 3) {
-            throw new IllegalValueException("INVALID_WEIGHT_INPUT");
+        if (argumentList.length < 3 || argumentList.length > 4) {
+            throw new IllegalValueException("Invalid add weight command");
```
Comment (NayChi-7) [inline src/main/java/seedu/duke/command/AddCommand.java:236]: Maybe it is better to introduce a constant for the error message for better readability?

File: src/main/java/seedu/duke/command/AddCommand.java [hunk 2]
```diff
@@ -254,8 +254,6 @@ private void addWeightAndFat(String[] argumentList) throws IllegalValueException
             }
         } catch (NumberFormatException e) {
             throw new IllegalValueException("Weight and fat percentage should be numerical");
-        } catch (DateTimeParseException e) {
-            throw new IllegalValueException("Date should be in the format dd-mm-yyyy");
```
Comment (NayChi-7) [inline src/main/java/seedu/duke/command/AddCommand.java:258]: Similarly, you might want to introduce constants for display message

**Review by NayChi-7 — APPROVED** [review]
